# Theme
theme: jekyll-theme-cayman

# Site identity
title: Backward Parabolic Positivity Barriers for the Xi Flow
description: Preprint and notebook
lang: en
timezone: Australia/Melbourne

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Canonical URL settings
url: "https://kschatz.github.io"
baseurl: "/rh-xi-backward-parabolic-barrier"

# Plugins supported on GitHub Pages
plugins:
  - jekyll-sitemap

  # Cayman theme option (Github download zip and tar.gz at top of page)
show_downloads: false
