theme: jekyll-theme-cayman
title: Backward Parabolic Positivity Barriers for the Xi Flow
description: Preprint â€” DOI 10.5281/zenodo.17636625
markdown: kramdown

url: "https://kschatz.github.io"
baseurl: "/rh-xi-backward-parabolic-barrier"

plugins:
  - jekyll-sitemap
